name: Tests

on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  build:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # We test multiple Windows shells because of prior stdout buffering issues
      # filed against Grunt. https://github.com/joyent/node/issues/3584
      - name: Run PowerShell tests
        run: "npm test # PowerShell" # Pass comment to PS for easier debugging
        shell: powershell
        if: startsWith(matrix.os, 'windows')
